### ISSUE TITLE
after installation with vim-plug no commands present

### ISSUE THREAD

**Issue by nerakhon** [justinmk/vim-gtfo#33]
After installing the plugin on OS X 10.11 with vim-plug the plugin doesn't get loaded. Any debugging data I can provide?

**Comment by justinmk** [comment]
Try restarting Vim? What is the output of

    :map g

**Comment by nerakhon** [comment]
v  gx            <Plug>NetrwBrowseXVis                                                                                                                                                                                                                                                                                                                                      
n  gx            <Plug>NetrwBrowseX                                                                                                                                                                                                                                                                                                                                         
n  goT         * :<C-U>call gtfo#open#term(getcwd(), "")<CR>                                                                                                                                                                                                                                                                                                                
n  goF         * :<C-U>call gtfo#open#file(getcwd())<CR>                                                                                                                                                                                                                                                                                                                    
n  got         * :<C-U>call gtfo#open#term("%:p:h", "")<CR>                                                                                                                                                                                                                                                                                                                 
n  gof         * :<C-U>call gtfo#open#file("%:p")<CR> 

but :got :gof :goT :goF isn't found am I missing something in vim logic?

**Comment by nerakhon** [comment]
Hmm thats weird the commands work via \got \gof etc, any cue what might be wrong?

**Comment by justinmk** [comment]
There aren't any commands yet, only mappings (`got`, etc.) and a function (`gtfo#open#term()`)

**Comment by nerakhon** [comment]
Ok my misunderstanding :) thx!
