### ISSUE TITLE
got issue - unable to open directories on different drives

### ISSUE THREAD

**Issue by AssailantLF** [justinmk/vim-gtfo#36]
Say my working directory is `C:\Users\Me\` or anywhere on the C drive. If I have a file anywhere on the W drive in my current buffer, say `W:\stuff\foo.txt`, and I use `got` to open a terminal to the stuff directory, it will open a terminal to `C:\`. Similarly, if the working directory is `W:\`, any files on `C:\` will just open to `W:\` in the terminal.

I'm not sure if this is because I used the windows `subst` command to make the W drive (I don't currently have other drives to test on), but it seems like maybe a condition needs to be added that changes drives before changing directories. Just my two cents though, you probably know better.
Using a normal install of Vim, and Windows 10.

Also sorry for [Issue 35](https://github.com/justinmk/vim-gtfo/issues/35) :|

**Comment by justinmk** [comment]
Confirmed for `got`. It works for `gof` though, right?

**Comment by AssailantLF** [comment]
Yeah, gof works correctly as long as [Git-for-Window's unix tools aren't in my path](https://github.com/justinmk/vim-gtfo/issues/34).

**Comment by AssailantLF** [comment]
Also confirmed that it's not because of subst. It happens with any separate drive.

**Comment by justinmk** [comment]
Thanks for the reports. Let me know if anything goes wrong.
