### ISSUE TITLE
gof not working (Windows 10)

### ISSUE THREAD

**Issue by serge-rgb** [justinmk/vim-gtfo#37]
`got` opens a Git shell on my Windows machine in my working directory, but `gof` opens This PC. `goF` gets me the Documents folder. 

What can I do to give more information that may be useful?

Thanks!

**Comment by justinmk** [comment]
After the `elseif s:iswin` in `gtfo#open#file`, add:

    echom '!start explorer '.(l:validfile ? '/select,'.shellescape(l:path, 1) : shellescape(l:dir, 1))

Then let me know the result of that. If it doesn't get hit, we'll need to figure out why as well.

**Comment by serge-rgb** [comment]
In `C:\gtfoTest`
with no file open:

```!start explorer '.'```

opening test.txt:

```!start explorer 'C:\gtfoTest'```

New info: The bug goes away when I comment-out `set shellslash` in my vimrc.

**Comment by justinmk** [comment]
@serge-rgb Thanks for the hint, that helps a lot.  It's rather odd to use `set shellslash` with `shell=cmd`, was that intentional?

Latest version should fix your issue.

**Comment by serge-rgb** [comment]
Thanks! :)

To answer your question, I like forward slashes better in Vim. I copied it from some vimrc
